version: "3.8"

services:
  user-service:
    build: .
    ports:
      - "5002:5001"
    environment:
      - MONGODB_URI=mongodb://user-service-mongo:27017
    depends_on:
      - user-service-mongo

  user-service-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
